Cafeteria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Queseriademisinti.urls")),
]

Queseriademisinti/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from Queseriademisinti import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('principal/',views.ProductoClientListView.as_view(), name='principal'),
    #### Menu #####
    path('menu/',views.ProductoClientListView.as_view(), name='cliente'),
    #### Compra_venta ########
     path('Historial/',views.CompraVentaListView.as_view(), name='historial'),
     path('Su_Historial/',views.list_Client_historial, name='cliente_historial'),
    ####### Quejas #########
    path('Quejas_y_sugerencias/',views.list_Client_Queja, name='quejas'),
    path('administrador/Quejas_y_sugerencias/',views.QuejasListView.as_view(), name='admin_quejas'),
    path('Quejas/add/',views.AddQueja, name='add_queja'),
    ######## Respuestas #########
    path('respuestas/',views.RespuestasListView.as_view(), name='respuesta'),
    path('tus_respuestas/',views.list_Client_respuesta, name='user_respuesta'),
    path('respuestas/add/<int:pk>/',views.AddRespuesta, name='add_repuesta'),
    path('respuestas/edit/<int:pk>/',views.RespuestaUpdateView, name='edit_repuesta'),
    path('respuestas/delete/<int:pk>/',views.RespuestaDeleteView.as_view(), name='eliminar_respuesta'),
    ### Pedido #####
    path('pedidos/edit/<int:pk>/',views.AddCompras, name='edit_pedido'),
    path('pedidos/',views.PedidoListView.as_view(), name='pedido'),
    path('pedidos_cliente/',views.list_cliente_buys, name='pedido_cliente'),
    path('pedidos/add/<int:pk>/',views.AddPedido, name='add_pedido'),
    path('pedidos/delete/<int:pk>/',views.PedidoDeleteView.as_view(), name='eliminar_pedido'),
    ############# Gestionar Trabajador###########
    path('trabajador/',views.TrabajadorListView.as_view(),name='trabajador'),
    path('trabajador/addAdmin/',views.TrabajadorCreateAdminView.as_view(),name='add_admin'),
    path('trabajador/addDependiente/',views.TrabajadorCreateDependienteView.as_view(),name='add_dependiente'),
    path('trabajador/addRepartidor/',views.TrabajadorCreateRepartidoView.as_view(),name='add_repartidor'),
    path('trabajador/edit/<int:pk>/',views.TrabajadorUpdateView.as_view(),name='editar_trabajador'),
    path('trabajador/delete/<int:pk>/',views.TrabajadorDeleteView.as_view(), name='eliminar_trabajador'),
    ############# Gestionar producto #############
    path('producto/',views.ProductoListView.as_view(),name='producto'),
    path('producto/add/',views.createProducto,name='add_producto'),
    path('producto/edit/<int:pk>/',views.ProductoUpdateView.as_view(),name='editar_producto'),
    path('producto/delete/<int:pk>/',views.ProductoDelteView.as_view(), name='eliminar_producto'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Queseriademisinti/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as T
from django.utils.html import mark_safe
from PIL import Image as Im
from django.core.validators import RegexValidator
validate_ci = RegexValidator('^\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{5}$', 'Carnet invalido')
validate_tfno = RegexValidator('^\+53\d{8}$', 'Teléfono invalido')
validate_name = RegexValidator('^[A-Za-záãäéëêíîóöúüñç\s]*$', 'Solo Letras,Introduzca Nombre y dos apellidos')
# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self,email,username,dir,ci,tfno,password=None,**extra_kwargs):
        if not email:
            raise ValueError('El usuario debe tener un correo electronico')
        
        user = self.model(email=self.normalize_email(email), 
                          username=username,
                          dir=dir, 
                          ci=ci, 
                          tfno=tfno,
                          **extra_kwargs                
        )
        user.is_cliente=True
        user.set_password(password)
        user.save()
        return user
    def create_superuser(self,email,username,dir,ci,tfno,password,**extra_kwargs):
        user = self.create_user(email,
                                username=username,
                                dir=dir, 
                                ci=ci, 
                                tfno=tfno,
                                password=password,
                                **extra_kwargs
        )
        user.is_cliente=False
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user
    
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=255, default="Cambio",validators=[validate_name])
    dir = models.CharField(max_length=255,blank=False, null=False)
    ci = models.CharField(max_length=11, unique=True, null=False, blank=False,validators=[validate_ci])
    tfno = models.CharField(max_length=50,validators=[validate_tfno],unique=True)
    is_cliente = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'dir', 'ci', 'tfno']

    def __str__(self):
        return self.username
    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self, app_label):
        return True
    @property
    def if_staf(self):
        return self.is_staff
    
class Producto(models.Model):
    nombre = models.CharField(max_length=255, unique=True, null=False, blank=False)
    foto = models.ImageField(upload_to='pics',null=True, blank=True)
    precio = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Precio',blank=False, null=False)
    cantidad = models.IntegerField(blank=False, null=False)
   
    class Meta:
        ordering = ['nombre']
    # para ver en adminDjango
    def img_tag(self): #new
        return mark_safe('<img src="/../../media/%s" width="150" height="150" />' % (self.foto))
    def save(self): # new
        super().save()
        img = Im.open(self.foto.path)
        # resize it
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.foto.path)
        
    def __str__(self):
        """Return String"""
        return self.nombre

class Quejas(models.Model):
    
    class tipoqueja (models.TextChoices):
        queja= 'Q', T('Queja')
        sugerencia= 'S', T('Sugerencia')
        
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=1, choices=tipoqueja.choices, null=False, blank=False)
    titulo = models.CharField(max_length=255, unique=True, null=False, blank=False)
    descripcion = models.CharField(max_length=255, null=False, blank=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)

    class Meta:
        ordering = ['fecha_creacion','tipo', 'titulo']

    def __str__(self):
        return "%s %s" % (self.tipo, self.titulo)

class Respuestas(models.Model):
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    quejas_id = models.ForeignKey(Quejas,on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=255, null=False, blank=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)
    
    class Meta:
        ordering = ['fecha_creacion']

    def __str__(self):
        return "%s" % (self.fecha_creacion)

class estadocoices (models.TextChoices):
        espera= 'E', T('Espera')
        aceptado= 'A', T('Aceptado')
        entregado = 'En', T('Entregado')
        
class Pedido(models.Model):
      
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    producto_id = models.ForeignKey(Producto,on_delete=models.CASCADE)
    estado = models.CharField(max_length=2, choices=estadocoices.choices, null=False, blank=False, default='E')
    cantidad = models.IntegerField(blank=False, null=False)
    class Meta:
        ordering = ['estado']
    
    def __str__(self):
        """Return String"""
        return self.estado
     
class Compra_venta(models.Model):
    pedido_id = models.ForeignKey(Pedido,on_delete=models.SET_NULL,null=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    total_pagado = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Total',blank=False, null=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)
    
    class Meta:
        ordering = ['fecha_creacion']

    def __str__(self):
        return "%s" % (self.fecha_creacion)

Queseriademisinti/templates/pages/pedido/add.html
{% extends "base_principal.html" %}
{% load static %}

{% block title %}
    Añadir Pedido
{% endblock title %}

{% block content %}
<div class="card shadow-lg">
    <div class="card-body p-5">
        <h1 class="fs-4 text-center card-title fw-bold mb-4">Añadir Pedido</h1>
        <form id="formulario" method = "POST" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="row">
                <div class=" mb-4 position-relative">
                <h6>Cantidad Disponible: {{object.cantidad}}</h6>
                    <label class="form-label">Cantidad a comprar</label>
                       {{forms.cantidad}}
                </div>
            
            </div>
            <div class="d-flex flex-row justify-content-center">
                <button id="enviar" type="submit" class="btn btn-primary">
                    Añadir Pedido
                </button>
                <a class="btn btn-danger ms-auto" href="{% url 'cliente' %}">Cancelar</a>
            </div>
        </form> 
    </div>
</div>
{% endblock content %}
{%block scripts%} 
{% if messages %}
{% for msg in messages %}
  <script>
    Swal.fire({'title' : "¡Error!" , "text" : "{{msg}}", "icon": "warning"})
  </script>
{% endfor %}
{% endif %}

{% comment %} <script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("formulario").addEventListener('submit', validarFormulario, ); 
    });
    function validarFormulario(evento) {
    evento.preventDefault();
    var cant = document.getElementById('id_cantidad').value;
    if(cant < 0) {
        alert('La cantidad no puede ser negativa');
        return;
    }
    if else()
    else
        alert('Pedido Añadido');
        return this.submit();
    
    
    }
</script> {% endcomment %}
{%endblock scripts%}

Queseriademisinti/templates/pages/pedido/delete.html
{% extends "base_principal.html" %}
{% load static %}
{%load grupos_tag %}
{% block title %}
    Eliminar Pedido
{% endblock title %}

{% block content %}
<div class="card shadow-lg">
    <div class="card-body p-5">
        <h1 class="fs-4 text-center card-title fw-bold mb-4">Eliminar Pedido</h1>
        <div class="content">
            <p class="fs-6">¿Está usted seguro que quiere eliminar el pedido seleccionado?</p>
            <ul><h2 class="fs-5">Pedido:</h2>
                <li>
                    Usuario:<strong>{{ object.user_id.username }}</strong>  
                </li>
                <li>
                    Producto:<strong>{{ object.producto_id }}</strong>
                </li>
                <li>
                    {%if object.estado == "En"%}
                    Estado:<strong>Entregado</strong>
                    {%endif%}
                    {%if object.estado == "A"%}
                    Estado:<strong>Aceptado</strong>
                    {%endif%}
                    {%if object.estado == "E"%}
                    Estado:<strong>Espera</strong>
                    {%endif%}
                </li>
                      
            </ul>
        <form method="POST" autocomplete="off" id="formulario">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Si, estoy seguro">
            {%if request.user|has_group:"cliente"%}
                <a class="text-decoration-none" href="{% url 'pedido_cliente' %}">
                    <button type="button" class="btn btn-secondary">Cancelar</button>
                </a>
                {%else%}
                <a class="text-decoration-none" href="{% url 'pedido' %}">
                    <button type="button" class="btn btn-secondary">Cancelar</button>
                </a>
            {%endif%}
        </form>
    </div>
</div>
{% endblock content %}
{%block scripts%} 
{%endblock scripts%}

Queseriademisinti/templates/pages/pedido/edit.html
{% extends "base_principal.html" %}
{% load static %}

{% block title %}
    Editar Pedido
{% endblock title %}

{% block content %}
<div class="card shadow-lg">
    <div class="card-body p-5">
        <h1 class="fs-4 text-center card-title fw-bold mb-4">Editar Pedido</h1>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger sm mb-3 p-2" role="alert">
                    <h6>Ha ocurrido un error al intentar guardar la entidad</h6>
                </div>
            {% endif %}
            <h4>Esta seguro que desea cambiar el estado de este pedido</h4>
            <div class="mb-3">
                <label class="form-label">Usuario:<strong>{{pedido.user_id}}</strong></label>
            </div>
            <label class="form-label" for="nomb">Producto:<strong>{{pedido.producto_id}}</strong></label>
            <label class="form-label"> <img src="{{pedido.producto_id.foto.url| escape }}" alt={{pedido.producto_id}} width="100" height="100"></label>
            <div class="mb-3">
                
                <label class="mb-2 text-muted" for="nomb">Estado:</label>
                {{form.estado}}
            </div>
            
            <div class="d-flex flex-row justify-content-center">
                <button type="submit" class="btn btn-primary">
                    Editar
                </button>
                <a class="btn btn-danger ms-auto" href="{% url 'pedido' %}">Cancelar</a>
            </div>
            
        </form>
    </div>
</div>
{% endblock content %}

Queseriademisinti/templates/pages/pedido/index.html
{% extends 'base_principal.html' %}
{% load static %}
{% load grupos_tag %}
{% block title %}Pedidos{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {#Container principal#}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
            <div class="container mt-3 ">
                <h1 class="fs-5">Pedidos</h1>
            </div>

            <!--------------------------------------------------------------------------------------
                -----------------TABLA CON RESULTADOS DE TRABAJADORES------------------------------------
                -------------------------------------------------------------------------------------------->

            {% comment %} ----------------------------------------------------------------------------
            -------------------------------BOTON INSERTAR------------------------------------
            ---------------------------------------------------------------------------{% endcomment %}
            
            <!--------------------------------------------------------------------------------------
           -----------------FIN BOTON INSERTAR------------------------------------
           -------------------------------------------------------------------------------------------->

            <div class="card border-0">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="entidadTable" class="table table-hover table-sm ">
                            <thead>
                            <tr>
                                <th scope="col" class="text-center" style="width: 50%">Número</th>
                                <th scope="col" class="text-center" style="width: 50%">Usuario</th>
                                <th scope="col" class="text-center" style="width: 15%">Producto</th>
                                <th scope="col" class="text-center" style="width: 25%">Estado</th>
                                <th scope="col" class="text-center" style="width: 25%">Cantidad</th>
                                <th scope="col" class="text-center" style="width: 25%">Dirección</th>
                                    {% if perms.Queseriademisinti.change_pedido or perms.Queseriademisinti.delete_pedido%}
                                        <th scope="col" class="text-center" style="width: 10%">Opciones</th>
                                    {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% csrf_token %}
                            {% for pedido in object_list %}
                                <tr>
                                    
                                    <td class="text-center">{{ pedido.id}}</td>
                                    <td class="text-center">{{ pedido.user_id.username}}</td>
                                    <td class="text-center">{{ pedido.producto_id}}</td>
                                    {%if pedido.estado == "E"%}
                                        <td class="text-center">Espera</td>
                                    {%endif%}
                                    {%if pedido.estado == "A"%}
                                        <td class="text-center">Aceptado</td>
                                    {%endif%}
                                    {%if pedido.estado == "En"%}
                                        <td class="text-center">Entregado</td>
                                    {%endif%}
                                    <td class="text-center">{{ pedido.cantidad | escape }}</td>
                                    <td class="text-center">{{ pedido.user_id.dir}}</td>   
                                    {% if perms.Queseriademisinti.change_pedido or perms.Queseriademisinti.delete_pedido %}
                                        <td>
                                            {% if request.user|has_group:"repartidor" %}
                                            <a id="" class=" mx-1 px-1 text-decoration-none" title="Editar"
                                               href="{% url 'edit_pedido' pedido.id %}">
                                                <img class=""
                                                     src="{% static 'images/icons/pen.svg' %}"
                                                     alt="Modificar" width="14" height="14">
                                            </a>
                                        {% endif %}
                                        {% if request.user|has_group:"dependiente" %}
                                            <a id="" class=" mx-1 px-1 text-decoration-none"
                                               title="Eliminar"
                                               href="{% url 'eliminar_pedido' pedido.id %}">
                                               <img class=""
                                                     src="{% static 'images/icons/trash.svg' %}"
                                                     alt="Eliminar" width="14" height="14">
                                              
                                            </a>
                                        {% endif %}
                                        </td>
                                    {% endif %}
                                    
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
     <!--------------------------------------------------------------------------------------
       -----------------TABLA CON RESULTADOS DE LAS ENTIDADES------------------------------------
       -------------------------------------------------------------------------------------------->
    </main>
{% endblock content %}

{% block scripts %}
    <script type="application/javascript">
        $(function () {
            $('#entidadTable').DataTable({
                responsive: true,
                "language": {
                    url: '{% static 'DataTables/es-ES.json ' %}'
                }
            });
        });
    </script> 
{% if messages %}
    {% for msg in messages %}
        <script>
            Swal.fire({'title' : "¡Hecho!" , "text" : "{{msg}}", "icon": "success"})
        </script>
    {% endfor %}
{% endif %}
{% endblock scripts %}

Queseriademisinti/templates/pages/pedido/index_cliente.html
{% extends 'base_principal.html' %}
{% load static %}
{% load grupos_tag %}
{% block title %}Pedidos{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {#Container principal#}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
            <div class="container mt-3 ">
                <h1 class="fs-5">Pedidos</h1>
            </div>

            <!--------------------------------------------------------------------------------------
                -----------------TABLA CON RESULTADOS DE TRABAJADORES------------------------------------
                -------------------------------------------------------------------------------------------->

            {% comment %} ----------------------------------------------------------------------------
            -------------------------------BOTON INSERTAR------------------------------------
            ---------------------------------------------------------------------------{% endcomment %}
            
            <!--------------------------------------------------------------------------------------
           -----------------FIN BOTON INSERTAR------------------------------------
           -------------------------------------------------------------------------------------------->

            <div class="card border-0">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="entidadTable" class="table table-hover table-sm ">
                            <thead>
                            <tr>
                                <th scope="col" class="text-center" style="width: 50%">Número</th>
                                <th scope="col" class="text-center" style="width: 50%">Usuario</th>
                                <th scope="col" class="text-center" style="width: 15%">Producto</th>
                                <th scope="col" class="text-center" style="width: 25%">Estado</th>
                                <th scope="col" class="text-center" style="width: 25%">Cantidad</th>
                                {% if perms.Queseriademisinti.change_pedido or perms.Queseriademisinti.delete_pedido%}
                                <th scope="col" class="text-center" style="width: 10%">Opciones</th>
                            {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% csrf_token %}
                            {% for pedido in object_list %}
                                <tr>
                                    <td class="text-center">{{ pedido.id}}</td>
                                    <td class="text-center">{{ pedido.user_id.username}}</td>
                                    <td class="text-center">{{ pedido.producto_id}}</td>
                                    {%if pedido.estado == "E"%}
                                        <td class="text-center">Espera</td>
                                    {%endif%}
                                    {%if pedido.estado == "A"%}
                                        <td class="text-center">Aceptado</td>
                                    {%endif%}
                                    {%if pedido.estado == "En"%}
                                        <td class="text-center">Entregado</td>
                                    {%endif%}
                                    <td class="text-center">{{ pedido.cantidad | escape }}</td>
                                    {% if perms.Queseriademisinti.delete_pedido %}
                                        <td>
                                        {% if request.user|has_group:"cliente" %}
                                            <a id="" class=" mx-1 px-1 text-decoration-none"
                                               title="Eliminar"
                                               href="{% url 'eliminar_pedido' pedido.id %}">
                                               <img class=""
                                                     src="{% static 'images/icons/trash.svg' %}"
                                                     alt="Eliminar" width="14" height="14">
                                            </a>
                                        {% endif %}
                                        </td>
                                    {% endif %} 
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

{% block scripts %}
    <script type="application/javascript">
        $(function () {
            $('#entidadTable').DataTable({
                responsive: true,
                "language": {
                    url: '{% static 'DataTables/es-ES.json ' %}'
                }
            });
        });
    </script>
{% if messages %}
    {% for msg in messages %}
        <script>
            Swal.fire({'title' : "¡Hecho!" , "text" : "{{msg}}", "icon": "success"})
        </script>
    {% endfor %}
{% endif %}
{% endblock scripts %}