Cafeteria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Queseriademisinti.urls")),
]

Queseriademisinti/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from Queseriademisinti import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('principal/',views.ProductoClientListView.as_view(), name='principal'),
    #### Menu #####
    path('menu/',views.ProductoClientListView.as_view(), name='cliente'),
    #### Compra_venta ########
     path('Historial/',views.CompraVentaListView.as_view(), name='historial'),
     path('Su_Historial/',views.list_Client_historial, name='cliente_historial'),
    ####### Quejas #########
    path('Quejas_y_sugerencias/',views.list_Client_Queja, name='quejas'),
    path('administrador/Quejas_y_sugerencias/',views.QuejasListView.as_view(), name='admin_quejas'),
    path('Quejas/add/',views.AddQueja, name='add_queja'),
    ######## Respuestas #########
    path('respuestas/',views.RespuestasListView.as_view(), name='respuesta'),
    path('tus_respuestas/',views.list_Client_respuesta, name='user_respuesta'),
    path('respuestas/add/<int:pk>/',views.AddRespuesta, name='add_repuesta'),
    path('respuestas/edit/<int:pk>/',views.RespuestaUpdateView, name='edit_repuesta'),
    path('respuestas/delete/<int:pk>/',views.RespuestaDeleteView.as_view(), name='eliminar_respuesta'),
    ### Pedido #####
    path('pedidos/edit/<int:pk>/',views.AddCompras, name='edit_pedido'),
    path('pedidos/',views.PedidoListView.as_view(), name='pedido'),
    path('pedidos_cliente/',views.list_cliente_buys, name='pedido_cliente'),
    path('pedidos/add/<int:pk>/',views.AddPedido, name='add_pedido'),
    path('pedidos/delete/<int:pk>/',views.PedidoDeleteView.as_view(), name='eliminar_pedido'),
    ############# Gestionar Trabajador###########
    path('trabajador/',views.TrabajadorListView.as_view(),name='trabajador'),
    path('trabajador/addAdmin/',views.TrabajadorCreateAdminView.as_view(),name='add_admin'),
    path('trabajador/addDependiente/',views.TrabajadorCreateDependienteView.as_view(),name='add_dependiente'),
    path('trabajador/addRepartidor/',views.TrabajadorCreateRepartidoView.as_view(),name='add_repartidor'),
    path('trabajador/edit/<int:pk>/',views.TrabajadorUpdateView.as_view(),name='editar_trabajador'),
    path('trabajador/delete/<int:pk>/',views.TrabajadorDeleteView.as_view(), name='eliminar_trabajador'),
    ############# Gestionar producto #############
    path('producto/',views.ProductoListView.as_view(),name='producto'),
    path('producto/add/',views.createProducto,name='add_producto'),
    path('producto/edit/<int:pk>/',views.ProductoUpdateView.as_view(),name='editar_producto'),
    path('producto/delete/<int:pk>/',views.ProductoDelteView.as_view(), name='eliminar_producto'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Queseriademisinti/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as T
from django.utils.html import mark_safe
from PIL import Image as Im
from django.core.validators import RegexValidator
validate_ci = RegexValidator('^\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{5}$', 'Carnet invalido')
validate_tfno = RegexValidator('^\+53\d{8}$', 'Teléfono invalido')
validate_name = RegexValidator('^[A-Za-záãäéëêíîóöúüñç\s]*$', 'Solo Letras,Introduzca Nombre y dos apellidos')
# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self,email,username,dir,ci,tfno,password=None,**extra_kwargs):
        if not email:
            raise ValueError('El usuario debe tener un correo electronico')
        
        user = self.model(email=self.normalize_email(email), 
                          username=username,
                          dir=dir, 
                          ci=ci, 
                          tfno=tfno,
                          **extra_kwargs                
        )
        user.is_cliente=True
        user.set_password(password)
        user.save()
        return user
    def create_superuser(self,email,username,dir,ci,tfno,password,**extra_kwargs):
        user = self.create_user(email,
                                username=username,
                                dir=dir, 
                                ci=ci, 
                                tfno=tfno,
                                password=password,
                                **extra_kwargs
        )
        user.is_cliente=False
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user
    
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=255, default="Cambio",validators=[validate_name])
    dir = models.CharField(max_length=255,blank=False, null=False)
    ci = models.CharField(max_length=11, unique=True, null=False, blank=False,validators=[validate_ci])
    tfno = models.CharField(max_length=50,validators=[validate_tfno],unique=True)
    is_cliente = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'dir', 'ci', 'tfno']

    def __str__(self):
        return self.username
    def has_perm(self,perm,obj=None):
        return True
    def has_module_perms(self, app_label):
        return True
    @property
    def if_staf(self):
        return self.is_staff
    
class Producto(models.Model):
    nombre = models.CharField(max_length=255, unique=True, null=False, blank=False)
    foto = models.ImageField(upload_to='pics',null=True, blank=True)
    precio = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Precio',blank=False, null=False)
    cantidad = models.IntegerField(blank=False, null=False)
   
    class Meta:
        ordering = ['nombre']
    # para ver en adminDjango
    def img_tag(self): #new
        return mark_safe('<img src="/../../media/%s" width="150" height="150" />' % (self.foto))
    def save(self): # new
        super().save()
        img = Im.open(self.foto.path)
        # resize it
        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.foto.path)
        
    def __str__(self):
        """Return String"""
        return self.nombre

class Quejas(models.Model):
    
    class tipoqueja (models.TextChoices):
        queja= 'Q', T('Queja')
        sugerencia= 'S', T('Sugerencia')
        
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=1, choices=tipoqueja.choices, null=False, blank=False)
    titulo = models.CharField(max_length=255, unique=True, null=False, blank=False)
    descripcion = models.CharField(max_length=255, null=False, blank=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)

    class Meta:
        ordering = ['fecha_creacion','tipo', 'titulo']

    def __str__(self):
        return "%s %s" % (self.tipo, self.titulo)

class Respuestas(models.Model):
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    quejas_id = models.ForeignKey(Quejas,on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=255, null=False, blank=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)
    
    class Meta:
        ordering = ['fecha_creacion']

    def __str__(self):
        return "%s" % (self.fecha_creacion)

class estadocoices (models.TextChoices):
        espera= 'E', T('Espera')
        aceptado= 'A', T('Aceptado')
        entregado = 'En', T('Entregado')
        
class Pedido(models.Model):
      
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    producto_id = models.ForeignKey(Producto,on_delete=models.CASCADE)
    estado = models.CharField(max_length=2, choices=estadocoices.choices, null=False, blank=False, default='E')
    cantidad = models.IntegerField(blank=False, null=False)
    class Meta:
        ordering = ['estado']
    
    def __str__(self):
        """Return String"""
        return self.estado
     
class Compra_venta(models.Model):
    pedido_id = models.ForeignKey(Pedido,on_delete=models.SET_NULL,null=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    total_pagado = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Total',blank=False, null=False)
    fecha_creacion = models.DateField(blank=False, null=False, auto_now=True)
    
    class Meta:
        ordering = ['fecha_creacion']

    def __str__(self):
        return "%s" % (self.fecha_creacion)

Queseriademisinti/templates/pages/quejas/add.html
{% extends "base_principal.html" %}
{% load static %}

{% block title %}
    Añadir Quejas
{% endblock title %}

{% block content %}
<div class="card shadow-lg">
    <div class="card-body p-5">
        <h1 class="fs-4 text-center card-title fw-bold mb-4">Añadir Quejas</h1>
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger sm mb-3 p-2" role="alert">
                    <h6>Ha ocurrido un error al intentar guardar la queja</h6>
                </div>
            {% endif %}
            <div class="mb-3">
                <label class="mb-2 text-muted" for="nomb">Titulo</label>
                {{form.titulo}}
                {%if form.titulo.errors%}
                <div class="alert alert-danger sm m-1 p-2 small" role="alert">
                {% for error in form.titulo.errors %}{{ error }}{% endfor %}
                </div>
                {%endif%}
            </div>
            <div class="mb-3">
                <label class="mb-2 text-muted" for="pass">Tipo</label>
                {{form.tipo}}
                
            </div>
            <div class="mb-3">
                <label class="mb-2 text-muted" for="nomb">Descripcion</label>
                {{form.descripcion}}
                {%if form.descripcion.errors%}
                <div class="alert alert-danger sm m-1 p-2 small" role="alert">
                {% for error in form.descripcion.errors %}{{ error }}{% endfor %}
                </div>
                {%endif%}
            </div>

            <div class="d-flex flex-row justify-content-center">
                <button type="submit" class="btn btn-primary">
                    Añadir
                </button>
                <a class="btn btn-danger ms-auto" href="{% url 'quejas' %}">Cancelar</a>
            </div>
            
        </form>
    </div>
</div>
{% endblock content %}

Queseriademisinti/templates/pages/quejas/admin_index.html
{% extends 'base_principal.html' %}
{% load static %}

{% block title %}Gestionar Trabajador{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {#Container principal#}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
            <div class="container mt-3 ">
                <h1 class="fs-5">Gestionar Quejas y Sugerencias</h1>
            </div>
            
            <!--------------------------------------------------------------------------------------
                -----------------TABLA CON RESULTADOS DE TRABAJADORES------------------------------------
                -------------------------------------------------------------------------------------------->

           
            <div class="card border-0">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="entidadTable" class="table table-hover table-sm ">
                            <thead>
                            <tr>
                                <th scope="col" class="text-center" style="width: 10%">Fecha</th>
                                <th scope="col" class="text-center" style="width: 10%">tipo</th>
                                <th scope="col" class="text-center" style="width: 10%">Nombre</th>
                                <th scope="col" class="text-center" style="width: 10%">Titulo</th>
                                {% if perms.Queseriademisinti.change_quejas or perms.Queseriademisinti.delete_quejas %}
                                    <th scope="col" class="text-center" style="width: 10%">Opciones</th>
                                {% endif %}
                            </tr>
                            </thead>
                            <tbody>
                            {% csrf_token %}
                            {% for quejas in object_list %}
                                <tr>
                                    <td class="text-center">{{ quejas.fecha_creacion}}</td>
                                    {%if quejas.tipo == 'Q'%}
                                    <td class="text-center">Queja</td>
                                    {%else%}
                                    <td class="text-center">Sugerencia</td>
                                    {%endif%}
                                    <td class="text-center">{{ quejas.usuario_id.username }}</td>
                                    <td class="text-center">{{ quejas.titulo}} </td>
                                    {% if perms.Queseriademisinti.change_quejas or perms.Queseriademisinti.delete_quejas %}
                                        <td>
                                            {% if perms.bugfinder.change_quejas %}
                                                <a id="" class=" mx-1 px-1 text-decoration-none" title="Añadir Respuesta"
                                                   href="{% url 'add_repuesta' quejas.id %}">
                                                   <img class="" src="{% static 'images/icons/plus-circle.svg' %}"
                                                   alt="Añadir Respuesta" width="16" height="16">
                                                </a>
                                            {% endif %}
                                        </td>
                                    {% endif %}
                                </tr>
                                <!-- Modal -->
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
     <!--------------------------------------------------------------------------------------
       -----------------TABLA CON RESULTADOS DE LAS ENTIDADES------------------------------------
       -------------------------------------------------------------------------------------------->
    </main>

{% endblock content %}

{% block scripts %}
{% if messages %}
    {% for msg in messages %}
        <script>
            Swal.fire({'title' : "¡Hecho!" , "text" : "{{msg}}", "icon": "success"})
        </script>
    {% endfor %}
{% endif %}
    <script type="application/javascript">
        $(function () {
            $('#entidadTable').DataTable({
                responsive: true,
                "language": {
                    url: '{% static 'DataTables/es-ES.json ' %}'
                }
            });
        });
    </script>
{% endblock scripts %}

Queseriademisinti/templates/pages/quejas/index.html
{% extends 'base_principal.html' %}
{% load static %}

{% block title %}Quejas y Sugerencias{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {#Container principal#}
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-5 scrollarea">
            <div class="container mt-3 ">
                <h1 class="fs-5">Quejas y Sugerencias</h1>
            </div>

            <!--------------------------------------------------------------------------------------
                -----------------TABLA CON RESULTADOS DE TRABAJADORES------------------------------------
                -------------------------------------------------------------------------------------------->

            {% comment %} ----------------------------------------------------------------------------
            -------------------------------BOTON INSERTAR------------------------------------
            ---------------------------------------------------------------------------{% endcomment %}
            {% if perms.bugfinder.add_quejas %}
                <div class="p-1">
                    <!-- Botón INSERTAR-->
                    <a type="button" href="{% url 'add_queja'%}"
                       class="btn p-0 border me-2  "
                       style="background-color: white"
                       title="Insertar Trabajador">
                        <button class="btn rounded-0">
                            <img class="" src="{% static 'images/icons/plus-circle.svg' %}"
                                 alt="Insertar Trabajador" width="16" height="16">
                            Añadir Quejas o Sugerencia
                        </button>
                    </a>
                </div>
            {% endif %}
            <!--------------------------------------------------------------------------------------
           -----------------FIN BOTON INSERTAR------------------------------------
           -------------------------------------------------------------------------------------------->

            <div class="card border-0">
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="entidadTable" class="table table-hover table-sm ">
                            <thead>
                            <tr>
                                <th scope="col" class="text-center" style="width: 10%">fecha_creacion</th>
                                <th scope="col" class="text-center" style="width: 10%">tipo</th>
                                <th scope="col" class="text-center" style="width: 10%">Nombre</th>
                                <th scope="col" class="text-center" style="width: 10%">Titulo</th>
                                <th scope="col" class="text-center" style="width: 10%">Descripción</th>
                                {% comment %} {% if perms.Queseriademisinti.change_quejas or perms.Queseriademisinti.delete_quejas %}
                                    <th scope="col" class="text-center" style="width: 10%">Opciones</th>
                                {% endif %} {% endcomment %}
                            </tr>
                            </thead>
                            <tbody>
                            {% csrf_token %}
                            {% for quejas in object_list %}
                                <tr>
                                    <td class="text-center">{{ quejas.fecha_creacion}}</td>
                                    {%if quejas.tipo == 'Q'%}
                                    <td class="text-center">Queja</td>
                                    {%else%}
                                    <td class="text-center">Sugerencia</td>
                                    {%endif%}
                                    <td class="text-center">{{ quejas.usuario_id.username }}</td>
                                    <td class="text-center">{{ quejas.titulo}}</td>
                                    <td class="text-center">{{ quejas.descripcion}}</td>
                                    {% comment %} {% if perms.Queseriademisinti.change_quejas or perms.Queseriademisinti.delete_quejas %}
                                        <td>
                                            {% if perms.bugfinder.change_quejas %}
                                                <a id="" class=" mx-1 px-1 text-decoration-none" title="Añadir Comentario"
                                                   href="">
                                                   <img class="" src="{% static 'images/icons/plus-circle.svg' %}"
                                                   alt="Añadir Respuesta" width="16" height="16">
                                                </a>
                                            {% endif %}
                                            {% if perms.bugfinder.change_quejas %}
                                                <a id="" class=" mx-1 px-1 text-decoration-none" title="Editar"
                                                   href="">
                                                    <img class=""
                                                         src="{% static 'images/icons/pen.svg' %}"
                                                         alt="Modificar" width="14" height="14">
                                                </a>
                                            {% endif %}
                                            {% if perms.bugfinder.delete_quejas %}
                                                <a id="" class=" mx-1 px-1 text-decoration-none"
                                                   title="Eliminar"
                                                   href="">
                                                   <img class=""
                                                         src="{% static 'images/icons/trash.svg' %}"
                                                         alt="Eliminar" width="14" height="14">
                                                  
                                                </a>
                                            {% endif %}
                                        </td>
                                    {% endif %} {% endcomment %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
     <!--------------------------------------------------------------------------------------
       -----------------TABLA CON RESULTADOS DE LAS ENTIDADES------------------------------------
       -------------------------------------------------------------------------------------------->
    </main>
{% endblock content %}

{% block scripts %}
{% if messages %}
    {% for msg in messages %}
        <script>
            Swal.fire({'title' : "¡Hecho!" , "text" : "{{msg}}", "icon": "success"})
        </script>
    {% endfor %}
{% endif %}
    <script type="application/javascript">
        $(function () {
            $('#entidadTable').DataTable({
                responsive: true,
                "language": {
                    url: '{% static 'DataTables/es-ES.json ' %}'
                }
            });
        });
    </script>
{% endblock scripts %}